# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@var" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/8212e1aa-5cd6-4b04-b483-e58570bf70ac";
    fsType = "btrfs";
    options = [ "subvol=@tmp" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/45EC-E308";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/media/Seagate" = {
    device = "/dev/disk/by-uuid/3ce5b29b-f89f-43d5-8ae7-e14791b0b3d3";
    fsType = "btrfs";
  };

  fileSystems."/media/WD" = {
    device = "/dev/disk/by-uuid/24e8471a-3b52-4693-ab3e-75a9a6b88fbd";
    fsType = "btrfs";
  };

  fileSystems."/media/Kingston" = {
    device = "/dev/disk/by-uuid/bfdece1a-bd67-40c9-abc0-10b28237b7da";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/faa05dc7-bd60-4b01-b927-7c32fa916b47"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
